steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_IMAGE_NAME}", "./calendar"]
    id: BUILD_CONTAINER
    waitFor: ["-"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE_NAME}"]
    id: PUSH_CONTAINER
    waitFor:
      - BUILD_CONTAINER

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "services",
        "replace",
        "multicontainers.yaml",
        "--region",
        "asia-northeast1",
      ]
    id: DEPLOY_CONTAINER
    waitFor:
      - PUSH_CONTAINER

substitutions:
  _REGISTRY: asia-northeast1-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}
  _IMAGE_NAME: ${_REGISTRY}/calendar:latest

images:
  - ${_IMAGE_NAME}

options:
  dynamic_substitutions: true
