apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/launch-stage: BETA
  name: datadog-sidecar-sample
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/container-dependencies: {"calendar":["dd-agent"]}
    spec:
      containers:
        - image: gcr.io/datadoghq/agent:latest
          name: dd-agent
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
        - image: ${REGISTRY}/calendar:latest
          name: calendar
          ports:
            - containerPort: 8080
          env:
          - name: DD_AGENT_HOST
            value: datadog
